services:
  nextjs:
    build:
      context: ./next/my-app
    ports:
      - '3001:3000'
      
  nestjs:
    build:
      context: ./nest/project-name
    ports:
      - '3000:3000'

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs
      - nestjs

